#!/bin/bash
#find -name "*.gif" -type f | LC_ALL=C sort -f | awk -F"/" '{print $NF}' | sed -e 's/\.gif//'
find -type f -name "*.gif" | rev | cut -d "/" -f 1 | cut -d '.' -f 2- | rev | LC_ALL=C sort -f
